/**
 * To make sure that "ids" are never repeated (for example on the "All articles" view) we're adding our own generated id to the article id.
 * Part that is generated by us is prefixed with "_CATEGORY_" string, this utility function returns everything before that prefix.
 * This way we make sure we get a "clean" version of an id, which then can be used for example to check if a following item is already saved in the "Read later" storage array.
 */
export const clearArticleId = (id: string) => {
	return id.split('_CATEGORY_')[0];
};
